# criando o client 1
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

# criando o client 2
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

# criando o account para o client 1
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "ade4f710-fc58-47ab-87e7-95aa3f5f0792"
}

###

# criando o account para o client 2
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "b67ac0aa-9b53-462b-9bbf-507e2f6a0f19"
}

###

# criando a transaction
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "2093535d-c410-477d-89fa-9b312fa71b3c",
    "account_id_to": "63067616-e10c-420a-8974-0876db193793",
    "amount": 10
}