# criando o client 1
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

# criando o client 2
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

# criando o account para o client 1
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "678489e4-44ec-4c53-bd3a-9acf84f56eff"
}

###

# criando o account para o client 2
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "5c1b80c4-9106-4db4-bb2a-0ddbe23c7694"
}

###

# criando a transaction
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "22d46470-6205-40df-a3c7-5c04e690adb2",
    "account_id_to": "c6a32fcc-d4ef-4432-8e50-156051eb3a39",
    "amount": 10
}