# criando o account
POST http://localhost:3003/create-account HTTP/1.1
Content-Type: application/json

{
    "id": "17af204f-1e4c-4b0f-9654-2e60a51bb32f",
    "balance": 100
}

###

# atualizando o balance
POST http://localhost:3003/update-balance HTTP/1.1
Content-Type: application/json

{
    "id": "17af204f-1e4c-4b0f-9654-2e60a51bb32f",
    "balance": 200
}

###

# listando os accounts
POST http://localhost:3003/accounts HTTP/1.1